USE vdl;
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test1@vdongli.com', 'test1', sha1('test'), now());
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test2@vdongli.com', 'test2', sha1('test'), now());
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test3@vdongli.com', 'test3', sha1('test'), now());
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test4@vdongli.com', 'test4', sha1('test'), now());
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test5@vdongli.com', 'test5', sha1('test'), now());
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test6@vdongli.com', 'test6', sha1('test'), now());
INSERT INTO `user` (email, nick_name, pass, reg_time) VALUES ( 'test7@vdongli.com', 'test7', sha1('test'), now());

INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount )values (NULL, 1, 1, 'follow', '2881802930', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 1, 'forward', '11142488790', 5, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 1, 'review', '11142488880', 6, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 4, 1, 'create', '介绍一下吉祥馄饨童卫路店', 5, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 2, 'forward', '11142847890', 8, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 2, 'review', '11414288880', 4, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 2, 'create', '推广中山陵旅游', 5, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 1, 'forward', '11412488790', 5, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 1, 'review', '11412488880', 8, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 4, 1, 'create', '介绍一下吉祥馄饨童卫路店', 5, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 2, 'forward', '11124847890', 3, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 2, 'review', '11412488880', 6, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 2, 'create', '推广中山陵旅游', 7, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 1, 'forward', '11142848790', 9, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 1, 'review', '11142848880', 2, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 4, 1, 'create', '介绍一下吉祥馄饨童卫路店', 20, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 2, 'forward', '11148247890', 9, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 2, 'review', '11414828880', 2, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 2, 'create', '推广中山陵旅游', 15, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 1, 'forward', '11142848790', 5, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 1, 'review', '11142484880', 5, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 4, 1, 'create', '介绍一下吉祥馄饨童卫路店', 13, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 4, 2, 'follow', '2300716544', 5, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 3, 2, 'forward', '11142874890', 5, 200, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 2, 2, 'review', '11414287880', 8, 300, 239);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 2, 'create', '推广中山陵旅游', 13, 150, 139);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2094993853', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2854158822', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2172508334', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1860032070', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2402779473', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2824988561', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2166990061', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2406597637', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1891990961', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1879064374', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1668703242', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2883678592', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1775186917', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1207483941', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2257742315', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1448752443', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1838622705', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2318136385', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1429532133', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1943516505', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2431065353', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1808131535', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2177282537', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1569921777', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2364563624', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2014845357', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2657949613', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1910143235', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2833612712', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2868564580', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1222806655', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2111684713', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2218577017', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2803085892', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2872838860', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2605199444', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2761237634', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1925998192', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2004898680', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2504396887', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2866977452', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2011294191', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2708122323', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2596489003', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1792963680', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2800811494', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1581896725', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2215889444', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2669348407', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2513390974', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1896280084', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2600659630', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2356279084', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2773374815', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2504034324', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2782291245', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2878688714', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2790946995', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1694985440', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2632996891', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2187893145', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2618706775', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2133187714', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2630864601', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2176264651', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2171839600', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2857935950', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2870627780', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2359674903', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2795681000', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2368323460', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2194030732', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2869272434', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1895053967', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2139641265', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1697784581', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2554439790', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1869838170', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2010151772', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1431225871', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2773974033', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2806781320', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2755970824', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2135691754', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2129112215', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2503308070', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2656988795', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2885901741', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2795225504', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2675940697', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2810589084', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1879414904', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2424233651', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2570952292', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2354349937', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2083052681', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2806406934', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2866320084', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2731218197', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2634559127', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2416994553', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2117023060', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2870302760', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2132073487', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2703743503', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1909364995', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2860887404', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2431702450', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1080379564', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2402735562', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1804196195', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1685378124', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2819773914', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2489382045', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1463343352', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2466892071', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2772943433', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1094043564', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2422579795', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2648720953', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2873102792', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2762746787', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2821125310', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2841615334', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1880691820', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2419807821', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2425134504', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2827488310', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2679722950', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2191646072', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1469728054', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1431013437', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2730385945', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1680149281', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2499056441', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2618524780', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1932976172', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2345019135', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2200853011', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2159495832', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2500740934', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2327309400', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2741348117', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2875863310', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2198164720', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2530504524', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2043708061', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2873569184', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2791226033', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2655620311', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2202571737', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1873275205', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2441968665', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2399022787', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2859592182', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1825449653', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2749893394', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1965992635', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2396254135', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2826053884', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1845561981', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1277309313', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1996525985', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1966841422', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2523847013', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2815319600', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2816996524', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2042552787', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1975930981', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1826743107', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1417736602', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1653449043', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1196006521', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2774946790', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1413290585', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1062802185', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1426107951', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1955812263', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2456574690', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1397323170', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1896025495', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1403220955', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2152255384', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2542503007', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2865154824', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2340389672', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2725499325', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2865418434', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1934149575', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1644272581', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1221284987', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1629372843', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1570910093', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2842359550', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2832460392', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2277668072', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '1740530163', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2779273493', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2840401464', 6, 100, 39);
INSERT INTO `task` (task_id, owner_id, publisher_id, task_type, task_info, task_offer, task_amount, task_finish_amount)values (NULL, 1, 1, 'follow', '2146087535', 6, 100, 39);

INSERT INTO `ader` (email, nick_name, task_amount) values('ad1@ad.ad', 'ad1', 1);
INSERT INTO `ader` (email, nick_name, task_amount) values('ad2@ad.ad', 'ad2', 1);
INSERT INTO `ader` (email, nick_name, task_amount) values('ad3@ad.ad', 'ad3', 1);
INSERT INTO `ader` (email, nick_name, task_amount) values('ad4@ad.ad', 'ad4', 1);

INSERT INTO `do_task` (task_id, user_id, status) values(1, 1, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(1, 2, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(1, 3, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(1, 4, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(2, 1, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(2, 2, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(2, 3, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(2, 4, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(3, 1, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(3, 2, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(3, 3, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(3, 4, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(4, 1, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(4, 2, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(4, 3, 'unfinish');
INSERT INTO `do_task` (task_id, user_id, status) values(4, 4, 'unfinish');
